<?php namespace Model\Selected;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class App extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'created' => ORM::field('datetime'),
			'app_id' => ORM::field('int[11]'),
			'img' => ORM::field('char[45]'),
			'page' => ORM::field('int[11]'),
		);

	}
}