<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Comment extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$relationships = array(        
            'comment'  => ORM::belongs_to('\\Model\\app'),
        );

		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'msg' => ORM::field('char[45]'),
			'created' => ORM::field('datetime'),
			'app_id' => ORM::field('int[11]'),
			'status' => ORM::field('numeric[4]'),
		);

	}
}