<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Screen extends ORM {
	
	public $primary_key = 'id';
	//public $foreign_key = array('\\Model\\User' => 'user_type_id', '\\Model\\user\\Type' => 'id');

	function _init()
	{
		
		self::$relationships = array(        
            'app'  => ORM::belongs_to('\\Model\\app'),
        );

		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'screen' => ORM::field('char[255]'),
			//'password' => ORM::field('char[45]'),
			//'email' => ORM::field('char[45]'),
			//'type' => ORM::field('int[11]'),
			//'status' => ORM::field('int[11]'),
			'app_id' => ORM::field('int[11]'),
		);

	}
}