<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class User extends ORM {
	
	public $primary_key = 'id';
	//public $foreign_key = array('\\Model\\User' => 'user_type_id', '\\Model\\user\\Type' => 'id');

	function _init()
	{
		

		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'user_name' => ORM::field('char[45]'),
			'password' => ORM::field('char[45]'),
			'name' => ORM::field('char[255]'),
			'email' => ORM::field('char[45]'),			
			'status' => ORM::field('int[11]'),
			'section_id' => ORM::field('int[11]'),
		);

	}
}